$('#tn-subnav-promo-button').addClass('btn-dark btn-lg');
$('.tn-cart-buttons__secondary-action').addClass('btn-dark btn-lg');
$('.tn-register-brief-button').addClass('btn-dark btn-lg');
$('.tn-additional-events__continue-shopping-link').addClass('btn-dark btn-lg');
$('.tn-additional-events__production-season-detail-link').addClass('btn-dark btn-lg');
$('.tn-link').addClass('btn-dark btn-lg');
$('.tn-timer').addClass('btn-dark btn-lg');
$('a.btn.btn-info.btn-block.tn-register-button').addClass('btn-dark btn-lg');
$('#tn-subnav-promo-code').addClass('form-control');
$('#tn-apply-promo').addClass('form-inline');
$('.tn-event-detail__unavailable-text').addClass('btn-dark btn-lg');
$('.col-xs-12').addClass('col-lg-12').removeClass('col-xs-12');
$('.col-sm-6').removeClass('col-sm-6');
$('.tn-logout-link').addClass('btn-dark btn-lg');
$('.tn-account-info-link').addClass('btn-dark btn-lg');
$('.tn-prod-season-header__image-wrapper').addClass('col-md-6');
$('.calendar').addClass('table');
$('.tn-add-donation-button').addClass('btn-dark btn-lg');
$('.col-sm-pull-4').removeClass('col-sm-pull-4');
$('.col-lg-pull-3').removeClass('col-lg-pull-3');
$('.col-lg-push-9').removeClass('col-lg-push-9');
$('.col-sm-push-8').removeClass('col-sm-push-8');
$('.col-sm-pull-2').removeClass('col-sm-pull-2');
$('.col-sm-push-10').removeClass('col-sm-push-10');
$('.tn-detail-production-text-toggle-link').addClass('btn-dark').removeClass('btn-default');
$('.tn-prod-season-header').addClass('container');
$('.tn-event-detail').addClass('container');
$('.tn-event-detail__additional-events-container').addClass('col');
$('.tn-event-detail__main-container').addClass('col');
$('.tn-component-contact-permissions__settings__item').addClass('card').addClass('col');
$('.tn-register-button').removeClass('btn-info');
$('.tn-component-contact-permissions__settings').addClass('row');
$('#dismiss_contact_permissions').addClass('btn-dark').addClass('btn-lg');
$('#save_contact_permissions').addClass('btn-dark').addClass('btn-lg');
$('.tn-detail-production-text-toggle-link').remove();
$('a.btn.btn-default').removeClass('btn-default').addClass('btn-dark');
$('a.btn.btn-primary').removeClass('btn-primary').addClass('btn-dark');
$('.tn-add-donation-button').addClass('btn-dark');
$('#dismiss_contact_permissions').addClass('btn-dark');
$('#save_contact_permissions').addClass('btn-dark');
