$('#tn-subnav-promo-button').addClass('btn-dark btn-lg');
$('.tn-cart-buttons__secondary-action').addClass('btn-dark btn-lg');
$('.tn-register-brief-button').addClass('btn-dark btn-lg');
$('.tn-additional-events__continue-shopping-link').addClass('btn-dark btn-lg');
$('.tn-additional-events__production-season-detail-link').addClass('btn-dark btn-lg');
$('.tn-link').addClass('btn-dark btn-lg');
$('.tn-timer').addClass('btn-dark btn-lg');
$('a.btn.btn-info.btn-block.tn-register-button').addClass('btn-dark btn-lg');
$('#tn-subnav-promo-code').addClass('form-control');
$('#tn-apply-promo').addClass('form-inline');
$('.tn-event-detail__unavailable-text').addClass('btn-dark btn-lg');
$('.col-xs-12').addClass('col-lg-12').removeClass('col-xs-12');
$('.col-sm-6').removeClass('col-sm-6');
$('.tn-logout-link').addClass('btn-dark btn-lg');
$('.tn-account-info-link').addClass('btn-dark btn-lg');
$('.calendar').addClass('table');
$('.tn-add-donation-button').addClass('btn-dark btn-lg');
