$('#tn-subnav-promo-button').addClass('btn-wine btn-lg');
$('.tn-cart-buttons__secondary-action').addClass('btn-wine btn-lg');
$('.tn-additional-events__continue-shopping-link').addClass('btn-wine btn-lg');
$('.tn-additional-events__production-season-detail-link').addClass('btn-wine btn-lg');
$('.tn-link').addClass('btn-wine btn-lg');
$('.tn-timer').addClass('btn-wine btn-lg');
$('a.btn.btn-info.btn-block.tn-register-button').addClass('btn-wine btn-lg');
$('#tn-subnav-promo-code').addClass('form-control');
$('#tn-apply-promo').addClass('form-inline');
$('.tn-event-detail__unavailable-text').addClass('btn-wine btn-lg');
$('.tn-prod-season-header__image').addClass('rounded-circle');
$('#tn-events-list-view > div.tn-event-listing-view__results-container > ul > li:nth-child(1) > div > a > img').find('img').addClass('rounded-circle');
$("div.tn-prod-list-item__property").find('a').addAttr('class', "rounded-circle");
